### ISSUE TITLE
HttpProcessor issue

### ISSUE THREAD

**Issue by didalgolab** [sashirestela/cleverclient#13]
Unfortunately I've found serious issue with the client. The fact that `HttpProcessor` is shared between all endpoints, and that each `HttpProcessor.createProxy()` replaces `metadata` and `urlBuilder` in it, it makes the whole client broken.

Consider the following example:
```java
public class MultiServiceDemo extends AbstractDemo {

    public void demoCallMultiService() {
        // First do something with moderations...
        openAI.moderations();
        // Now play a little with models...
        openAI.models();
        // Now go back to moderation...
        var moderationRequest = ModerationRequest.builder()
                .input(Arrays.asList(
                        "I am not sure what to think about it."))
                .build();
        var futureModeration = openAI.moderations().create(moderationRequest);
        var moderationResponse = futureModeration.join();
        moderationResponse.getResults().stream()
                .forEach(System.out::println);
    }

    public static void main(String[] args) {
        var demo = new MultiServiceDemo();
        demo.addTitleAction("Little multiservice demo", demo::demoCallMultiService);
        demo.run();
    }
}
```

which generates the following exception:
```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "io.github.sashirestela.cleverclient.metadata.Metadata$Method.getUrl()" because "methodMetadata" is null
	at io.github.sashirestela.cleverclient.http.URLBuilder.build(URLBuilder.java:22)
	at io.github.sashirestela.cleverclient.http.HttpProcessor.resolve(HttpProcessor.java:61)
	at io.github.sashirestela.cleverclient.http.HttpInvocationHandler.invoke(HttpInvocationHandler.java:35)
	at jdk.proxy2/jdk.proxy2.$Proxy4.create(Unknown Source)
	at io.github.sashirestela.openai.demo.MultiServiceDemo.demoCallMultiService(MultiServiceDemo.java:19)
```

---

There is also an issue with SSE end of stream marker: [DONE]. It is passed in a constructor `CleverClient(String urlBase, List<String> headers, HttpClient httpClient, String endOfStream)`, but ultimately ends in a static variable: `CleverClientSSE.setEndOfStream(endOfStream)`, which means it's not client-local anymore.

**Comment by sashirestela** [comment]
Hey @didalgolab, thanks for detecting this issue. I'm going to work on that and hopefully fix it on weekend.

**Comment by didalgolab** [comment]
Maybe in class HttpProcessor, fields `metadata` and `urlBuilder` could be moved to `HttpInvocationHandler` class, thus making the `HttpProcessor` stateless? It's just a thought...

**Comment by sashirestela** [comment]
@didalgolab I have fixed the HttpProcessor issue.

Regarding the endOfStream marker, it is a kind of configuration variable, because I don't think you could have different markers for the same API. In the future we could refactor the library to have something like a Configurator class. So, no changes for this so far.
